<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>linktiger.http</groupId>
    <artifactId>parent</artifactId>
    <version>3.14.10-SNAPSHOT</version>
  </parent>

  <artifactId>okhttp-tests</artifactId>
  <name>OkHttp Tests</name>

  <dependencies>
    <dependency>
      <groupId>com.squareup.okio</groupId>
      <artifactId>okio</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>okhttp</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${okhttp3.groupId}</groupId>
      <artifactId>okhttp-testing-support</artifactId>
      <version>${okhttp3.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>${okhttp3.groupId}</groupId>
      <artifactId>okhttp-tls</artifactId>
      <version>${okhttp3.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>${okhttp3.groupId}</groupId>
      <artifactId>okhttp-urlconnection</artifactId>
      <version>${okhttp3.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>${okhttp3.groupId}</groupId>
      <artifactId>mockwebserver</artifactId>
      <version>${okhttp3.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>${okhttp3.groupId}</groupId>
      <artifactId>logging-interceptor</artifactId>
      <version>${okhttp3.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
